In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression

In [3]:
path="/home/iamchiranjeeb/Desktop/amita/real_estate_price_size_year.csv"
df = pd.read_csv(path)
df.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [4]:
df.shape

(100, 3)

In [5]:
df.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [6]:
X = df[['size','year']]
y = df['price']

In [7]:
model = LinearRegression()

In [8]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
model.intercept_

-5772267.017463278

In [10]:
model.coef_

array([ 227.70085401, 2916.78532684])

In [12]:
model.score(X,y)

0.7764803683276793

# F-Statistics

In [13]:
f_regression(X,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [14]:
f_stat = f_regression(X,y)[0]
f_stat

array([285.92105192,   0.85525799])

In [15]:
p_values = f_regression(X,y)[1]
p_values

array([8.12763222e-31, 3.57340758e-01])

In [16]:
p_values.round(3)

array([0.   , 0.357])

# Summary Table

In [17]:
reg_summary = pd.DataFrame(data=X.columns.values,columns=['Features'])
reg_summary

Features
0     size
1     year

In [18]:
reg_summary['Coefficients'] = model.coef_

In [19]:
reg_summary['P_Value'] = p_values.round(3)

In [20]:
reg_summary

Features  Coefficients  P_Value
0     size    227.700854    0.000
1     year   2916.785327    0.357

# Prediction

In [22]:
p1 = model.predict([[643.09,2015]])
p1

array([251487.55831903])

In [23]:
p2 = model.predict([[789.86,2020]])
p2

array([299491.1392959])

In [24]:
p3 = model.predict([[643.09,2020]])
p3

array([266071.48495323])